import type { Metadata } from "next";

import candybeans from "next/font/local"

import "./globals.css";
import Providers from "@/utils/Providers"

const font = candybeans({ src: "./fonts/candy-beans.otf" })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} antialiased`}
      >
        <Providers>
        {children}
        </Providers>
      </body>
    </html>
  );
}
